### ISSUE TITLE
<Response [504]> for spamcheck 1.0.2

### ISSUE THREAD

**Issue by uayyappa** [Tesorio/spamcheck-python#4] opened 2017-09-13 06:06 UTC
I am unable to get response from spamcheck for following request : 
 
spamcheck.check('Content-Type: multipart/alternative;\n boundary="===============8077893510432256978=="\nMIME-Version: 1.0\nDate: Wed, 13 Sep 2017 09:58:05 +0530\nX-Sender: iton@imailgrid.com\nSender: iton@imailgrid.com\nX-Receiver: web-vzvuv@mail-tester.com\nX-envId: U0pbBVpaQkoFB0VQWQ8EQBEEURRcBQlW\nX-CampaignID: U1NBUFdVURFFX1JKCgNaWk0QAVARC1ULVhEWUw\nX-Feedback-ID: UVhfPUFL:U1NBUFdVURFFX1JKCgNaWk0QAVARC1ULVhEWUw:PAYIC1I8BAwP:imailgrid\nX-Report-Abuse-To: abuse@imailgrid.com\nFrom: Iton Team<iton@imailgrid.com>\nTo: web-vzvuv@mail-tester.com\nSubject: =?utf-8?q?Morning_Wishes?=\nErrors-To: iton@imailgrid.com\nList-Unsubscribe: <https://verify.citimedia.com/unSubConform?c_Id=4638&emailId=web-vzvuv@mail-tester.com\nList-Unsubscribe-Post: List-Unsubscribe=One-Click\nPrecedence: bulk\nReply-To: Iton Team<iton@imailgrid.com>\nMessage-ID: <20170913042805.7562.99346.b12d11b8fe@localhost.localdomain>\n\n--===============8077893510432256978==\nMIME-Version: 1.0\nContent-Type: text/plain; charset="utf-8"\nContent-Transfer-Encoding: base64\n\nSGkKCkl0b24gVGVhbSB3aXNoZXMgeW91IGdvb2QgbW9ybmluZwoKdGhhbmsgeW91\n\n--===============8077893510432256978==--', report=True)

Please solve my problem

**Comment by FabioFleitas** [comment] 2017-09-15 18:55
Thanks for bringing this to our attention @uayyappa. Will take a look and see what's going on and deploy a fix.

**Comment by FabioFleitas** [comment] 2017-09-15 18:58
Hi @uayyappa I just tried reproducing the error and it seems like it's working now. Can you check and see if it works for you?

**Comment by FabioFleitas** [comment] 2017-09-17 19:00
Seems like this is a duplicate of #5 and that was resolved. Let us know if there are any other issues.

**Closed as completed by FabioFleitas** 2017-09-17 19:00 UTC
